### ISSUE TITLE
Slow delete

### ISSUE THREAD

**Issue by ghost** [hsoft/dupeguru#175]
dupe guru found  about 13k of duplicate files. After hours of waiting for them to be deleted i gave up. I tried it several times still deleting files is very slow. Than i tried moving the files else where to delete them manually. 
Moving the still existing 11k of files only took 30 seconds.

I have this problem on Windows 7 64 and MacOS Snow Leopard and Lion.
On Lion moving the files is impossible because dupe guru crashes :(

**Comment by rudolphos** [comment]
I use SSD, but it's still very slow to delete 6000 files using direct method and recycle bin method. Basically it seems both ways would take around 30 mins.

**Comment by rudolphos** [comment]
I use SSD, but it's still very slow to delete 6000 files using direct method and recycle bin method. Basically it seems both ways would take around 30 mins. DG is deleting around at speed 2-3 files per second.
