### ISSUE TITLE
Make folder selection reset process easier

### ISSUE THREAD

**Issue by ghost** [hsoft/dupeguru#228]
From email:

> I have found all your software very useful and straightforward. I was wondering if it would be possible to include a capability within the "Folder Selection Window". Regardless of how many folders are listed, it would be very helpful to click inside the list and be able to "select all" and press the "delete" key to be able to remove all listed folders. There are several keyboard shortcuts throughout the program, but none in this window. 
> 
> When numerous folders are listed, it would be nice to be able to do a "Command+A" to select all, and then just press the "delete" key, rather than having to select the top folder, scroll down to the last folder and press "shift" and click on last folder, then press the "-" button on the bottom of the window.

**Comment by lihuelworks** [comment]
To add to this, I'd be amazing if there was a keyboard to open an image inside the app (to check and compare between dupliactes). I tried enter, space, "o", but no dice. 

Edit: Nevermind, my small brain couldn't catch the "details" feature. Thanks Glubsy!

**Comment by glubsy** [comment]
There is, if you are in "Picture mode" and press "details".
