### ISSUE TITLE
Firefox link on hardcoded.net fails.

### ISSUE THREAD

**Issue by wedi** [hsoft/dupeguru#269]
Probably no one really clicks on that link but I just discovered that the footer link to Mozilla on http://www.hardcoded.net/ is pointing to http://www.hardcoded.net/www.mozilla.org/en-US/firefox/ which of course results in an error.
:+1: for the whitestripes though.

**Comment by hsoft** [comment]
Since the website redesign, this links doesn't exist anymore...
