### ISSUE TITLE
Please add hotkey to "Mark Selected"

### ISSUE THREAD

**Issue by audiomuze** [hsoft/dupeguru#334]
As per subject, it'd be handy to be able to mark selected tracks without having to use the mouse and navigate the menu.

**Comment by hsoft** [comment]
The hotkey for that is already supposed to Space. Does it work for you?

**Comment by audiomuze** [comment]
It does, thanks.  Didn't see it marked in the menu so didn't know.  Should read docs I guess...my apologies.
