### ISSUE TITLE
Possibility to start/pause/stop the folder scan

### ISSUE THREAD

**Issue by fabiosirna** [hsoft/dupeguru#363]
Sometimes I'm using DupeGuru SE on a laptop with an external hard disk. 
For larger folder and scan it would be great **to put in pause/stop the scan** and then start again. 

It happens sometimes when I move from home to office (and viceversa) and the scan was not yet completed.

**Comment by hsoft** [comment]
Could this be a duplicate to #241? @patrickatamaniuk is interested by this also. You might want to work with him to make this happen.

**Comment by fabiosirna** [comment]
yes, sure. I searched the repository with wrong keywords and didn't noticed that. Sorry for bother you with a double request.
