### ISSUE TITLE
Why we can't select the first item in the group of dupe files?

### ISSUE THREAD

**Issue by madmax2** [hsoft/dupeguru#375]
There is a problem,
when the program scans and shows duplicate files

The problem is I can't select the first item in the group of dupe files

In many cases the first item is older versions than the selectable items
but i can't select the first item.

e.g. 
FileA 1.4
FileA 1.5
.
I can't select the FileA 1.4 because there is no checkbox, so I can only delete/move a newer version file.

**Comment by hsoft** [comment]
It's to prevent you from deleteing all members of a group. See https://www.hardcoded.net/dupeguru/help/en/faq.html#the-mark-box-of-a-file-i-want-to-delete-is-disabled-what-must-i-do
