### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by 1kakarot** [hsoft/dupeguru#378]
I found that on windows for version 4.0.0. the language selection in the options dialog has no effect. I keep getting english for any selection in the language dropdown menu even after restart.
I will try with ubuntu at home...

I want to make a locale folder for greek.
I want some guidance here.
I made a new folder in locale folder --> el\LC_MESSAGES and I modify-translate the *.po files.
The same for \qtlib\locale\el\LC_MESSAGES. Correct?
Also I guess I have to modify hscommon\trans.py, qt\preferences_dialog.py, qtlib\preferences.py to include an "el" part.
Do I miss something?

Thanks

**Comment by 1kakarot** [comment]
First of all, I saw the translator guide...
Yet, I can tell for sure that version se-3.9.1 works fine with greek and language setting-modification.
Version 4.0.0 seems to have something wrong - stays with english always... (I checked in ubuntu also).

**Comment by hsoft** [comment]
At the first look, it seems that you're right. That would be a regression. Thanks for reporting it, I'll look into it.

**Comment by hsoft** [comment]
Yup, that was a regression. It's fixed in the referenced commit.

**Comment by 1kakarot** [comment]
I wish I had found it first, but you know better your program.
