### ISSUE TITLE
Rebuild Windows packaging

### ISSUE THREAD

**Issue by hsoft** [hsoft/dupeguru#393]
Windows support [has been dropped with v4.0](https://github.com/hsoft/dupeguru#windows-maintainer-wanted) because the project lacks a Windows maintainer. If you'd like to step up to the task, great! You have to know however that your first challenge will be significant: the build system has to be redone.

The old Windows build system (you can see it if you checkout dupeGuru v3.x) was fragile, hardly reproducable and based on a proprietary system, [Advanced Installer](http://www.advancedinstaller.com/). To make the matter worse, it was a very old version.

That doesn't fly anymore. That system has to be remade. You, who would be dupeGuru's Windows maintainer, can use whatever open source tool you want, as long as the build is reproducable by anyone. I will help you in any way I can, but that help is inherently limited: I really don't know much about Windows.

There's a bit more details about this in #300.

**Comment by QuestionableChanges** [comment]
Why was the installer added then removed?
Is someone actively looking into Windows 10 compatibility?

**Comment by arsenetar** [comment]
@hsoft I got some initial work on the installer script committed.  Working through an issue with the venv / virtualenv and the `--system-site-packages` flag.  The binary scripts from the system packages are not available in the virtual environment.  This mainly just affects the pyrcc5 command in the makefile which I did not catch previously since I still had a cached result from an earlier run (I had turned off the `--system-site-packages` flag to debug an issue) .  Options could be to specify the pyrcc5 command on windows via an environment variable to make or not use the `--system-site-packages` flag on windows. Unless I am missing something which is due to my local setup.

**Comment by hsoft** [comment]
@arsenetar I remember that I had problems with virtualenvs on windows as well. In my dev env, I didn't use virtualenvs at all. Not clean, but at the time, I didn't see alternatives.

If you don't use `--system-site-packages`, you're not going to be able to import `PyQt5`, no?

**Comment by arsenetar** [comment]
@hsoft If I do not use `--system-site-packages` then I just have to install PyQt5 into the virtualenv and then it works fine.

**Comment by arsenetar** [comment]
@hsoft I got more updates to the windows packaging.  I added a Windows.md for now with some windows specific notes as well.  We  need to decide if these notes should go into the README.md or if you would like them separate.  Other files which are new are `requirements-windows.txt` and `setup.nsi`.  If we are okay with these files then I will be working through some final testing on the installers and executables then I will be ready ready for a PR. 

Side Note: looks like Send2Trash 1.4.0 broke windows functionality, I opened a issue over there.  If we want a working dupeGuru on windows Send2Trash needs to be held back or fixed.  I have just went back to 1.3.1 for now.

**Comment by hsoft** [comment]
Good news! I think you did the right thing using a separate file for Windows instructions. They're a bit lengthy to fit on the main README. We can add a link to it though.

I haven't looked at your changes with great attention yet, but I will try them when your PR is ready. I will have to dust-off my old win7 ISO and create a VM from it. The good news is that it's going to be a good test for the quality of your instructions: I will really have to start from scratch.

**Comment by arsenetar** [comment]
@hsoft Windows Installer builds are on the way, I just sent an email.

**Comment by hsoft** [comment]
@arsenetar Thanks! I've verified that the installer work in my window VM and I've updated [dupeGuru's webpage](https://www.hardcoded.net/dupeguru/)

**Comment by hsoft** [comment]
I think that we can close this issue now.

**Comment by hsoft** [comment]
Oh, as a closing comment: if anyone's interested in giving @arsenetar a hand, don't hesitate. I think there's a need in the build instructions department because it might be missing some details. If you look at #438, you'll see that I gave up trying to build the thing myself.
