### ISSUE TITLE
Ignore path

### ISSUE THREAD

**Issue by Gunni** [hsoft/dupeguru#408]
Hey,

I'd love to be able to enter a path that is in the scan selection but i want ignored/not checked for duplicates anyway.

Examples are:
- Steam Library
- Plex Library (Metadata folder)

**Comment by hsoft** [comment]
You mean https://www.hardcoded.net/dupeguru/help/en/folders.html#folder-states ?

**Comment by Gunni** [comment]
Sort of, if only: http://image.prntscr.com/image/88d83b8dde584b809766f5e9fe57fb05.png

I want E to be in the selected list but exclude E:\SteamLibrary

**Comment by hsoft** [comment]
Use the little arrow to open `E:` and go exclude your subfolder. Also, [Windows is not supported anymore](https://www.hardcoded.net/archive2015#2015-11-01)

**Comment by Gunni** [comment]
Oh, i didn´t see that.

I also didn´t know it wasn't supported anymore, sorry.
