### ISSUE TITLE
Bolding filenames changes the space the name takes up

### ISSUE THREAD

**Issue by rieje** [hsoft/dupeguru#418]
When checking for duplicates by content, the output for one copy of the file is bolded. This changes its size and makes it difficult to quickly compare with the other copies of the same file to see if the file name is exactly the same. How about changing the font colors and not bolding the "master" copy so that the filenames align correctly?

**Comment by hsoft** [comment]
Duplicate to #314 , so I'll close this, but otherwise, I agree with you. I'm only waiting for a pull request to that effect.
