### ISSUE TITLE
Support  for python 3.6

### ISSUE THREAD

**Issue by jlesage** [hsoft/dupeguru#427]
With Python 3.6, dupeGuru fails to starts:
```
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 74, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 59, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 24, in <module>
    from . import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from . import block, cache, exif, iphoto_plist, matchblock, matchexif, photo, prioritize, result_table, scanner # noqa
  File "/usr/share/dupeguru/core/pe/block.py", line 9, in <module>
    from ._block import NoBlocksError, DifferentBlockCountError, avgdiff, getblocks2 # NOQA
ModuleNotFoundError: No module named 'core.pe._block'
```
Renaming CPython extensions from `*cpython-35m-x86_64-linux-gnu.so` to `*cpython-36m-x86_64-linux-gnu.so` fixes the issue.

I'm wondering if it's possible to handle this in the build script.  Maybe automatically adding a symlink would be enough?

There are few extensions to handle:
```
# find /usr/share/dupeguru -name "*cpython-35m-x86_64*"
/usr/share/dupeguru/core/pe/_cache.cpython-35m-x86_64-linux-gnu.so
/usr/share/dupeguru/core/pe/_block.cpython-35m-x86_64-linux-gnu.so
/usr/share/dupeguru/qt/pe/_block_qt.cpython-35m-x86_64-linux-gnu.so
```

**Comment by hsoft** [comment]
Isn't this simply a case of having installed dupeGuru *before* you've updated your python install? If you re-install dupeguru from a clean slate, wouldn't you end up with properly named `.so` files?

**Comment by jlesage** [comment]
Yeah sorry I was using a pre-compiled package that was not built with python 3.6.  Sorry for the noise!

**Comment by alexivkin** [comment]
This problem happens on ubuntu 17.08 and probably 18.04. For anyone coming here from google the fix is to relink proper libs - ```

sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-36m-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/core/pe/_block.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-36m-x86_64-linux-gnu.so
sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-35m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-36m-x86_64-linux-gnu.so 
```

**Comment by GM-Script-Writer-62850** [comment]
@alexivkin Thanks
That made the deb located here work on xubuntu 18.04:
https://launchpad.net/%7Ehsoft/+archive/ubuntu/ppa/+sourcepub/7165907/+listing-archive-extra

**Comment by springfielddatarecovery** [comment]
Can confirm the work proposed by @alexivkin works for me. I had to change the "-35m" part as I was on a slightly different version experiencing similar problems, was certainly caused by libraries not being linked correctly by .deb installer.

**Comment by drajabr** [comment]
And here I copy paste changing "-36m" to -38m just being lazy to open text editor and paste edit there, also that would help another lazy person! :) 


sudo ln /usr/share/dupeguru/core/pe/_cache.cpython-38m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_cache.cpython-38m-x86_64-linux-gnu.so

sudo ln /usr/share/dupeguru/core/pe/_block.cpython-38m-x86_64-linux-gnu.so /usr/share/dupeguru/core/pe/_block.cpython-38m-x86_64-linux-gnu.so

sudo ln /usr/share/dupeguru/qt/pe/_block_qt.cpython-38m-x86_64-linux-gnu.so /usr/share/dupeguru/qt/pe/_block_qt.cpython-38m-x86_64-linux-gnu.so
