### ISSUE TITLE
dupeGuru Support Forum Vanished!

### ISSUE THREAD

**Issue by edwinbarton** [hsoft/dupeguru#432]
Might not be a new issue but is certainly one that needs attention in some form or another.  I clicked the link to the dupeGuru Support forum on the dupeGuru page at https://www.hardcoded.net/dupeguru/ only to discover that the link is invalid.  How are we supposed to get assistance from peer users of dupeGuru now?

**Comment by hsoft** [comment]
I closed it more than a year ago. I forgot to remove the links. There wasn't any peer assistance going on on this forum at all, only unanswered questions.
