### ISSUE TITLE
v4.0.3 for macOS crashes on launch

### ISSUE THREAD

**Issue by bahhhhh** [hsoft/dupeguru#454]
My MacBook Pro (Retina, 13-inch, Mid 2014) is running macOS 10.13.1 (17B48), and dupeGuru (4.0.3) crashes immediately upon launching it. Below is part of the crash log.

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Crashing on exception: <class 'NameError'>: name 'logging' is not defined
```

Let me know if you need more information.

**Comment by effndc** [comment]
I believe you need to delete the cache to clear this up, when I encountered this I just deleted the ~/Library/Application Support/dupeGuru contents and was able to start the app again.

**Comment by bahhhhh** [comment]
@effndc That did the trick! Thank you!
