### ISSUE TITLE
Dupeguru uninstall also removed other programs

### ISSUE THREAD

**Issue by liu3631** [hsoft/dupeguru#456]
I was in the process of cleaning my computer and uninstalling software I haven't used in a while. 
When I launched the dupeguru uninstaller it started saying 
"Deleting C:\Program Files\NameOfProgram"
"Deleting C:\Program Files\NameOfProgram2"
"Deleting C:\Program Files\NameOfProgram3"
...
When it "finished" a lot of programs have been removed from my computer, including some NVIDIA and Intel drivers. 
Don't know what happened but I'm reporting it. I am a Windows 7 user.

**Comment by arsenetar** [comment]
@liu3631 Do you know what version you had installed (x86 / x64)?

**Comment by arsenetar** [comment]
I think I might have the issue.  @liu3631 do you remember if you installed to the default directory?

**Comment by liu3631** [comment]
@arsenetar If I remember correctly I had the 64 bit version installed in the Program Files directory. I haven't mentioned it but the programs that have been uninstalled were both in C:/Program Files and C:/Program Files (x86)

**Comment by hsoft** [comment]
I've just received an email from someone who is very upset to have lost data after uninstalling and I'm thinking this might be related to this issue. Is this fix in the currently published version of dupeGuru for windows?

**Comment by arsenetar** [comment]
I have a built version, never did publish it though, just took care of that now.  The site now points to a version with the fixed installer.
