### ISSUE TITLE
dupeGuru 4.0.3 - installer languages (Windows)

### ISSUE THREAD

**Issue by smaragdus** [hsoft/dupeguru#461]
The installer of **dupeGuru** version **4.0.3** (**dupeguru_win64_4.0.3.exe**) allows only two languages to choose from- **Russian** and **Ukrainian**:

![dupeguru 4 0 3 - 2017-11-15 - 002](https://user-images.githubusercontent.com/9025757/32837062-add6b382-ca14-11e7-84d4-dec29489e2fc.png)

However after installation the program runs in **English**.

I suppose that the installer tries to use the system language and this erroneous behaviour comes from there. I happen to understand some **Russian** so I was able to go through the installation but such absurd behaviour (the installer tries to be smart but is actually dull) would discourage other users.

A possible workaround is the extraction of the installer.

Expected behaviour of the installer- it offers all (**16**) supported languages to choose from, not only **Russian** and **Ukrainian**.

**Comment by arsenetar** [comment]
I have updated the installer script which should force it to show all the languages in the selection dialog.  It seems the selection reduction is may not be desired.  The installer only supports 13 of the 16 languages right now.
