### ISSUE TITLE
Font Size Issue with non-standard font size settings in Windows 10

### ISSUE THREAD

**Issue by NumbGnat** [hsoft/dupeguru#504]
The font in the list of "more options" does not scale well with the other fonts on that dialog. I am using 150% scaling in my display properties.

![image](https://user-images.githubusercontent.com/1946849/39896537-74202a40-547c-11e8-967f-e9566d6e6299.png)

**Comment by arsenetar** [comment]
This is an issue with how the dialog is setup.  Looks like it might be caused partially by 
https://github.com/hsoft/dupeguru/blob/30b6e5c68d379b4aa9b037cec2593afe16d806e8/qt/se/preferences_dialog.py#L28
https://github.com/hsoft/dupeguru/blob/30b6e5c68d379b4aa9b037cec2593afe16d806e8/qt/se/preferences_dialog.py#L44

There is some additional dialog sizing which might have to be updated to completely fix this as well.

**Comment by arsenetar** [comment]
Just wondering do you see this on any of the other dialogs?

**Comment by NumbGnat** [comment]
It appears that it only happens on the standard mode options.  The music and picture dialogs appear properly.  Are Music and Pictures newer development?  Perhaps the Standard dialog is just older and not coded or laid to handle more modern display and font sizing mechanisms.

As a software architect/developer myself, I would probably just duplicate the Music dialog and simply modify it to apply to Standard settings. That would eliminate a ton of debugging time.  ;)

**STANDARD SETTINGS**
![image](https://user-images.githubusercontent.com/1946849/40391220-8b708c7c-5de5-11e8-98f6-a6bdf5815ec4.png)

**MUSIC SETTINGS**
![image](https://user-images.githubusercontent.com/1946849/40391250-a0a8d9aa-5de5-11e8-9d12-c2d01820efdf.png)

**PICTURE SETTINGS**
![image](https://user-images.githubusercontent.com/1946849/40391361-f4e22b0c-5de5-11e8-8280-d02a4645f71e.png)
