### ISSUE TITLE
Trojan:Win32/Fuery.B!cl ?! Is what Windows Defender reports when downloaded

### ISSUE THREAD

**Issue by Shtoomik** [hsoft/dupeguru#512]
Download from the website https://dupeguru.voltaicideas.net/

Found another build here that seems clean
https://portableapps.com/node/55981

**Comment by arsenetar** [comment]
This is odd, was clean originally.

**Comment by hsoft** [comment]
Virus scanner often misdetect viruses because of python being embedded in the app (the virus in question must have used python or something). That being said, this kind of detection is always worrying.

Part of why I don't want to deal with anything related Windows.

**Comment by Shtoomik** [comment]
[https://www.virustotal.com/#/file/1bfe7fd2e619d39a51db3256692219bd4445a785111fa4a7abcdef8b9879b120/detection
](https://www.virustotal.com/#/file/1bfe7fd2e619d39a51db3256692219bd4445a785111fa4a7abcdef8b9879b120/detection
)
[https://www.microsoft.com/en-us/wdsi/submission/d5a9bfd3-ab79-4151-a88f-4abc5bf7a384](https://www.microsoft.com/en-us/wdsi/submission/d5a9bfd3-ab79-4151-a88f-4abc5bf7a384)

seems like a false positive, also subitted it to MS
