### ISSUE TITLE
Download failed on  Windows 10: contained a virus and was deleted!

### ISSUE THREAD

**Issue by Foadsf** [hsoft/dupeguru#513]
I'm trying to download the windows binary from official webpage but I get a error:

> dupeGuru_win64_4.0.3.exe contained a virus and was deleted

**Comment by Shtoomik** [comment]
https://www.microsoft.com/en-us/wdsi/submission/d5a9bfd3-ab79-4151-a88f-4abc5bf7a384

Submitted it to MS - it's a false positive.

Duplicate of #512.

**Comment by arsenetar** [comment]
I have checked this again, false positive report seems to have updated Windows Defender. Now it does not delete executable.
