### ISSUE TITLE
Results window off screen

### ISSUE THREAD

**Issue by AcornPirate** [hsoft/dupeguru#521]
When I first started using DupeGuru I had three monitors, now I only have one and the results window is off screen. I have tried a number of ways to pull the results window back to the main screen without success. I have even uninstalled and reinstalled DupeGuru and the results screen still remains off screen. Any assistance you may be able to provide with this would be greatly appreciated.

Thank you, 
Acorn Pirate

**Comment by furyritchie** [comment]
Click on the task bar icon for the second window (if it exists) and use Windows + Shift + Left/Right

**Comment by leebriangaskins** [comment]
Fix:
Close dupeGuru
Go to regedit.exe
Find key HKEY_CURRENT_USER\Software\Hardcoded Software\dupeGuru\ResultWindowRect
Delete the four numbers within this key.
Open dupeGuru

The result window will appear after a scan. It may be very small or in an odd place but you can see it.
