### ISSUE TITLE
Find duplicates in Folder B using Folder A for reference only

### ISSUE THREAD

**Issue by JustinReinhart** [hsoft/dupeguru#539]
The only issue I have with dopeGuru is that it still attempts to find duplicates in a folder I mark as reference. A lot of what I use dupeGuru for is being able to safely erase duplicates in Folder B using Folder A as a reference. However, dupeGuru takes it upon itself to also tell me duplicates of Folder A files that are also in Folder A. These duplicates are normal and I don't wish them to be targeted.  

I simply wish for the option of telling dupeGuru to exclude searching for duplicates within a reference folder but it should still use that folder as reference when examining other folders.

**Comment by a-raccoon** [comment]
I can't reproduce.
