### ISSUE TITLE
cx_Freeze error startup crash

### ISSUE THREAD

**Issue by torndar** [hsoft/dupeguru#542]
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\projects\dupeguru\env\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\projects\dupeguru\env\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "run.py", line 12, in <module>
  File "ExtensionLoader_PyQt5_QtCore.py", line 23, in <module>
  File "ExtensionLoader_PyQt5_QtCore.py", line 15, in __bootstrap__
  File "C:\Python36-x64\lib\imp.py", line 343, in load_dynamic
ImportError: Module use of python33.dll conflicts with this version of Python.

Python33.dll and Python36.dll are both in the application install folder and removing either one of them causes "not found" errors.

**Comment by arsenetar** [comment]
This might be an issue with cx_Freeze and/or the project configuration here.  I noticed a few issues last time I went to build a windows executable, do not remember if this was one of them.  I am considering switching to pyinstaller instead as it seems to work with less reconfiguration when python versions are changed / and updates.

**Comment by torndar** [comment]
If you do let me know and I'll gladly test.

**Comment by arsenetar** [comment]
I have updated the source at https://github.com/arsenetar/dupeguru/tree/542 to build using pyInstaller instead of cx_Freeze.  I continue to have issues with cx_Freeze and newer version of PyQt5 and python.
Attached here is an installer built using this source, it seems to work fine for me.  If you are building from source try that branch, otherwise try the attached version.

Installer: https://github.com/arsenetar/dupeguru/releases/download/4.0.3-InstallFix2/dupeGuru_win64_4.0.3.exe

**Comment by torndar** [comment]
Installs for me now. Giving it a test run.

**Comment by gemosley** [comment]
Can't get either 4.0.3 or 4.0.4 of dupeGuru to work. Same error as the start of this thread. pyInstaller link above doesn't seem to be there anymore. Is a working version available, do you know?
Thanks.

**Comment by arsenetar** [comment]
The current 4.0.4 version is built with pyInstaller.  The error at the top of this thread should be impossible with 4.0.4 when installed after uninstalling 4.0.3.  The files which cause this issue (and the scripts listed in the traceback are no longer present).  If you installed 4.0.4 without uninstalling 4.0.3 it is possible that there might be some file left from the 4.0.3 installation which can cause issues.

**Comment by gemosley** [comment]
Thanks, arsenetar. Uninstalling 4.0.3 was the answer. Working fine now.
